In [1]:
import pandas as pd

In [4]:
def generate_strings(input_list):
    output_list = []
    for s in input_list:
        output_list.append(s + " - Budget")
        output_list.append(s + " - Actual")
    return ", ".join(output_list)

input = ["FSE", "Group", "Single", "Total Paid", "Comp", "Total Distributed", "Drop Count", "Show Rate", "ATP", "Gross Ticket Revenue", "Amusement Taxes", "Park District Fee", "MLS Share of Revenue", "Net Ticket Revenue",
"Units Sold", "Avg. Per Unit", "Revenue Generated", "Less Projected Expenses", "Net Premium", "Merchandise (Net)", "Concessions (Net)", "Parking (Net)", "Total Net Per Cap (Net)", "Merchandise Per Cap (Net)", "Concessions Per Cap (Net)", "Parking Per Cap (Net)",
"Net Per Caps", "Merchandise (Gross)", "Concessions (Gross)", "Parking (Gross)", "Total Gross Per Cap", "Merchandise Per Cap (Gross)", "Concessions Per Cap (Gross)", "Parking Per Cap (Gross)", "Gross Per Caps", "Total Net MD Revenue"]
output = generate_strings(input)
print(output)

FSE - Budget, FSE - Actual, Group - Budget, Group - Actual, Single - Budget, Single - Actual, Total Paid - Budget, Total Paid - Actual, Comp - Budget, Comp - Actual, Total Distributed - Budget, Total Distributed - Actual, Drop Count - Budget, Drop Count - Actual, Show Rate - Budget, Show Rate - Actual, ATP - Budget, ATP - Actual, Gross Ticket Revenue - Budget, Gross Ticket Revenue - Actual, Amusement Taxes - Budget, Amusement Taxes - Actual, Park District Fee - Budget, Park District Fee - Actual, MLS Share of Revenue - Budget, MLS Share of Revenue - Actual, Net Ticket Revenue - Budget, Net Ticket Revenue - Actual, Units Sold - Budget, Units Sold - Actual, Avg. Per Unit - Budget, Avg. Per Unit - Actual, Revenue Generated - Budget, Revenue Generated - Actual, Less Projected Expenses - Budget, Less Projected Expenses - Actual, Net Premium - Budget, Net Premium - Actual, Merchandise (Net) - Budget, Merchandise (Net) - Actual, Concessions (Net) - Budget, Concessions (Net) - Actual, Parking (Net) - Budget, Parking (Net) - Actual, Total Net Per Cap (Net) - Budget, Total Net Per Cap (Net) - Actual, Merchandise Per Cap (Net) - Budget, Merchandise Per Cap (Net) - Actual, Concessions Per Cap (Net) - Budget, Concessions Per Cap (Net) - Actual, Parking Per Cap (Net) - Budget, Parking Per Cap (Net) - Actual, Net Per Caps - Budget, Net Per Caps - Actual, Merchandise (Gross) - Budget, Merchandise (Gross) - Actual, Concessions (Gross) - Budget, Concessions (Gross) - Actual, Parking (Gross) - Budget, Parking (Gross) - Actual, Total Gross Per Cap - Budget, Total Gross Per Cap - Actual, Merchandise Per Cap (Gross) - Budget, Merchandise Per Cap (Gross) - Actual, Concessions Per Cap (Gross) - Budget, Concessions Per Cap (Gross) - Actual, Parking Per Cap (Gross) - Budget, Parking Per Cap (Gross) - Actual, Gross Per Caps - Budget, Gross Per Caps - Actual, Total Net MD Revenue - Budget, Total Net MD Revenue - Actual

In [7]:
vert = pd.read_csv("Matchday Summary Data Template.csv")
vert

,Group,Metric,Budget,Actual,% to Goal,Match
0,Ticket Revenue,FSE,"5,700","5,668",0.994386,FIR0304
1,Ticket Revenue,Group,"7,960","4,393",0.551884,FIR0304
2,Ticket Revenue,Single,"1,888","4,103",2.173199,FIR0304
3,Ticket Revenue,Total Paid,15548,14164,0.910985,FIR0304
4,Ticket Revenue,Comp,3000,"3,169",1.056333,FIR0304
...,...,...,...,...,...,...
427,Net Per Cap,Merchandise Per Cap,1.135280768,1.46379655,1.289370,FIR0715
428,Net Per Cap,Concessions Per Cap,4.679948763,4.598032757,0.982496,FIR0715
429,Net Per Cap,Parking Per Cap,4.949472408,4.333380378,0.875524,FIR0715
430,Net Per Cap,Net Per Cap,10.76470194,10.39520969,0.965676,FIR0715
431,Total,Total Net Matchday Revenue,369277,493116,1.335355,FIR0715

In [8]:
vert = vert[["Metric", "Budget", "Actual", "Match"]]
vert

                         Metric       Budget       Actual    Match
0                           FSE        5,700        5,668  FIR0304
1                         Group        7,960        4,393  FIR0304
2                        Single        1,888        4,103  FIR0304
3                    Total Paid        15548        14164  FIR0304
4                          Comp         3000        3,169  FIR0304
..                          ...          ...          ...      ...
427         Merchandise Per Cap  1.135280768   1.46379655  FIR0715
428         Concessions Per Cap  4.679948763  4.598032757  FIR0715
429             Parking Per Cap  4.949472408  4.333380378  FIR0715
430                 Net Per Cap  10.76470194  10.39520969  FIR0715
431  Total Net Matchday Revenue       369277       493116  FIR0715

[432 rows x 4 columns]

In [13]:
#long to wide

budget_pivot = vert.pivot_table(index='Match', columns='Metric', values='Budget', aggfunc='sum')
budget_pivot.columns = [f"{col} - Budget" for col in budget_pivot.columns]
# Pivot actual column
actual_pivot = vert.pivot_table(index='Match', columns='Metric', values='Actual', aggfunc='sum')
actual_pivot.columns = [f"{col} - Actual" for col in actual_pivot.columns]

# Combine the pivoted DataFrames
result_df = pd.concat([budget_pivot, actual_pivot], axis=1).reset_index()
result_df

,Match,ATP - Budget,Amusement Taxes - Budget,Average Per Unit - Budget,Comp - Budget,Concessions Per Cap - Budget,Concessions Revenue - Budget,Drop Count - Budget,FSE - Budget,Gross Per Cap - Budget,...,Parking Revenue - Actual,Revenue Generated - Actual,Show Rate - Actual,Single - Actual,Total Distributed - Actual,Total Gross Per Cap Revenue - Actual,Total Net Matchday Revenue - Actual,Total Net Per Cap Revenue - Actual,Total Paid - Actual,Units Sold - Actual
0,FIR0304,30.69,-51122,276,3000,19.659719014.624289298,27510264709,"13,993","5,700",35.25949604,...,12613655444,43329,0.72,"4,103",17333,443385,452481,135224,14164,167
1,FIR0318,33.35,-24982,276,3000,19.660624844.680148741,12372029451,"6,293","4,700",35.95114258,...,6716328064,30635,0.51,773,6770,180651,204143,57916,5363,132
2,FIR0401,33.09,-25124,276,3000,25.249207144.679706463,16102429844,"6,377","4,700",41.53818541,...,9055539663,31127,0.65,"1,051",7623,234041,242235,77180,6241,121
3,FIR0408,32.48,-28074,276,3000,25.250095414.679871096,18334633981,"7,261","4,700",41.34965196,...,8780138031,30360,0.78,"1,496",10016,304029,281413,94173,7280,124
4,FIR0415,31.48,-30581,276,3000,25.250172114.679885311,20607238193,"8,161","5,700",41.19978124,...,8371535878,36501,0.77,"1,495",10708,318654,298901,95207,8259,143
5,FIR0429,30.51,-36514,276,3000,25.251042074.678999194,25387147042,"10,054","6,700",41.4012027,...,8072234585,52418,0.61,"1,181",10294,272356,296509,80030,8838,187
6,FIR0513,31.10,-51441,276,3000,25.250427444.684580257,35083465088,"13,894","5,700",41.10019929,...,11415148354,68582.75,0.79,"5,240",15855,481440,501078,136823,14227,279
7,FIR0520,30.55,-36102,276,3000,25.250282094.679905695,25061446449,"9,925","6,700",40.97996512,...,10950546020,54589,0.81,"2,480",15407,444703,442826,125969,12712,214
8,FIR0610,28.98,-51302,276,3000,25.251639824.675448143,37555569536,"14,873","8,075",41.06217134,...,15129366498,84978.5,0.73,"2,817",16413,489863,494904,138600,14354,409
9,FIR0708,29.35,-51375,276,3000,25.250103934.676708225,37123768759,"14,702","7,700",41.05967379,...,15223566650,75081,0.72,"6,174",20147,531346,586498,152014,18328,313
10,FIR0712,33.35,-25069,276,3000,33.384176766.410410823,21077140472,"6,314","4,710",52.34595866,...,7375929902,102489,0.68,"2,014",10850,353070,355927,90329,9445,494
11,FIR0715,31.33,-34071,276,3000,25.250514474.679948763,23064142747,"9,134","5,700",41.06034138,...,13140356802,93638,0.81,"3,596",16232,473829,493116,136260,13665,394

In [14]:
result_df.columns.tolist()

['Match',
 'ATP - Budget',
 'Amusement Taxes - Budget',
 'Average Per Unit - Budget',
 'Comp - Budget',
 'Concessions Per Cap - Budget',
 'Concessions Revenue - Budget',
 'Drop Count - Budget',
 'FSE - Budget',
 'Gross Per Cap - Budget',
 'Gross Ticket Revenue - Budget',
 'Group - Budget',
 'Less Projected Expenses - Budget',
 'MLS Share of Revenue - Budget',
 'Merchandise Per Cap - Budget',
 'Merchandise Revenue - Budget',
 'Net Per Cap - Budget',
 'Net Premium Revenue - Budget',
 'Net Ticket Revenue - Budget',
 'Park District Fee - Budget',
 'Parking Per Cap - Budget',
 'Parking Revenue - Budget',
 'Revenue Generated - Budget',
 'Show Rate - Budget',
 'Single - Budget',
 'Total Distributed - Budget',
 'Total Gross Per Cap Revenue - Budget',
 'Total Net Matchday Revenue - Budget',
 'Total Net Per Cap Revenue - Budget',
 'Total Paid - Budget',
 'Units Sold - Budget',
 'ATP - Actual',
 'Amusement Taxes - Actual',
 'Average Per Unit - Actual',
 'Comp - Actual',
 'Concessions Per Cap - Actual',
 'Concessions Revenue - Actual',
 'Drop Count - Actual',
 'FSE - Actual',
 'Gross Per Cap - Actual',
 'Gross Ticket Revenue - Actual',
 'Group - Actual',
 'Less Projected Expenses - Actual',
 'MLS Share of Revenue - Actual',
 'Merchandise Per Cap - Actual',
 'Merchandise Revenue - Actual',
 'Net Per Cap - Actual',
 'Net Premium Revenue - Actual',
 'Net Ticket Revenue - Actual',
 'Park District Fee - Actual',
 'Parking Per Cap - Actual',
 'Parking Revenue - Actual',
 'Revenue Generated - Actual',
 'Show Rate - Actual',
 'Single - Actual',
 'Total Distributed - Actual',
 'Total Gross Per Cap Revenue - Actual',
 'Total Net Matchday Revenue - Actual',
 'Total Net Per Cap Revenue - Actual',
 'Total Paid - Actual',
 'Units Sold - Actual']